### ISSUE TITLE
Docs review & validation, update.

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#259]
Is the content up to date? Technically accurate? Reads well and clearly. Screenshots reflect current products? Worked installation commands and examples are accurate and work. Check for assumptions like validation and authentication already being in place.
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/docs/issues/262
- [ ] https://github.com/epinio/docs/issues/270
- [ ] https://github.com/epinio/docs/issues/277
- [ ] https://github.com/epinio/docs/issues/278
- [ ] https://github.com/epinio/docs/issues/279
- [ ] https://github.com/epinio/docs/issues/280
- [ ] https://github.com/epinio/docs/issues/281
- [ ] https://github.com/epinio/docs/issues/282
- [ ] https://github.com/epinio/docs/issues/301
```
