### ISSUE TITLE
Review and update installation docs

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#277]
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/docs/issues/284
- [ ] https://github.com/epinio/docs/issues/285
- [ ] https://github.com/epinio/docs/issues/286
- [ ] https://github.com/epinio/docs/issues/287
- [ ] https://github.com/epinio/docs/issues/288
- [ ] https://github.com/epinio/docs/issues/289
- [ ] https://github.com/epinio/docs/issues/290
- [ ] https://github.com/epinio/docs/issues/291
- [ ] https://github.com/epinio/docs/issues/292
- [ ] https://github.com/epinio/docs/issues/293
- [ ] https://github.com/epinio/docs/issues/294
```
