### ISSUE TITLE
Review and update tutorial docs

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#278]
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/docs/issues/319
- [ ] https://github.com/epinio/docs/issues/320
- [ ] https://github.com/epinio/docs/issues/321
- [ ] https://github.com/epinio/docs/issues/322
```

**Comment by jhkrug** [comment]
All done
