### ISSUE TITLE
Review and update Explanation docs

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#279]
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/docs/issues/341
- [ ] https://github.com/epinio/docs/issues/342
- [ ] https://github.com/epinio/docs/issues/343
- [ ] https://github.com/epinio/docs/issues/344
```
