### ISSUE TITLE
Review and update How-tos

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#280]
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/docs/issues/345
- [ ] https://github.com/epinio/docs/issues/346
- [ ] https://github.com/epinio/docs/issues/347
- [ ] https://github.com/epinio/docs/issues/348
- [ ] https://github.com/epinio/docs/issues/349
- [ ] https://github.com/epinio/docs/issues/350
- [ ] https://github.com/epinio/docs/issues/351
- [ ] https://github.com/epinio/docs/issues/352
- [ ] https://github.com/epinio/docs/issues/353
```
